name: 'Contentful Changelist Sync'
description: 'Contentful Sync overlayed with Entries as specified by a "Changelist" (required content type)'
author: 'yan-kisen'
inputs:
  changelist-id:
    required: false
    description: 'Changelist ID to be queried & then overlayed ontop of the initial Contentful Sync'
outputs:
  something:
    description: 'surely this will output something...'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'red'
